version: '3'

services:
    php:
        build:
            context: src
            args:
                PHP_VERSION: ${PHP_VERSION}
                HOST_FILES_OWNER_UID: ${HOST_FILES_OWNER_UID}
                HOST_FILES_OWNER_NAME: ${HOST_FILES_OWNER_NAME}
                XDEBUG_CONFIG: "client_host=host.docker.internal"
                PHP_IDE_CONFIG: "serverName=Docker"
        container_name: ${COMPOSE_PROJECT_NAME}_php
        image: ${COMPOSE_PROJECT_NAME}_php:${PHP_VERSION}
        tty: true
        ports:
            - '${PROJECT_IP}:80:80'
        volumes:
            - './src:/var/www/sandbox'
#            - './docker/php/php.ini:/usr/local/etc/php/php.ini:ro'